spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true # 开启 console 访问
      settings:
        trace: true # 开启 h2 console 跟踪，方便调试
        web-allow-others: true # 允许console 远程访问 默认false
      path: /h2-console # h2 访问路径上下文

logging:
  level:
    com.hao.demo: debug