
spring:
  application:
    name: user-provider
  cloud:
    # 使用 spring cloud 提供的 zookeeper 连接启动器，配置前缀为 spring.cloud
    zookeeper:
      # zookeeper 连接地址，默认为 localhost:2181
      connect-string: 192.168.25.40:2181
      discovery:
        # true 表示当前服务需要注册到注册中心，默认就是 true
        register: true

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 20880
    # 使用 spring cloud 版本的 zookeeper 启动器，
    # 注册中心的配置不再在 dubbo 前缀下而是在 spring.cloud 前缀下
#  registry:
#    address: N/A
