# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/mall?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


MYSQL_HOST: localhost
domain: http://localhost

lab:
  worker-id: 1
  data-center-id: 1
logging:
  level:
    com.hao: debug