spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.25.43:9876
      bindings:
        output:
          destination: TopicOutput
        orderOutput:
          destination: TopicOrder